#!/bin/sh
######################################################
#
# Test various HOME environment variable settings.
#
######################################################

set -e

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname $0`/../..
    MH_OBJ_DIR=`cd $srcdir && pwd`; export MH_OBJ_DIR
fi

. "${MH_OBJ_DIR}/test/common.sh"

setup_test

start_test 'with non-null HOME'
run_test 'mhparam path' "${MH_TEST_DIR}/Mail"

start_test 'with null HOME'
HOME= run_test 'mhparam path' "${MH_TEST_DIR}/Mail"

start_test 'with no HOME'
unset HOME
run_test 'mhparam path'  "${MH_TEST_DIR}/Mail"

finish_test
exit ${failed}
